import axios from 'axios';

async function fetchFromNSE(url) {
  try {
    const response = await axios.get(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        'Accept': 'application/json, text/plain, */*'
      }
    });
    return { success: true, data: response.data };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

export async function fetchTopGainers(limit = 10) {
  const url = 'https://www.nseindia.com/api/live-analysis-variations?index=NIFTY%2050';
  const result = await fetchFromNSE(url);
  if (result.success && result.data?.gainers) {
    return { success: true, data: result.data.gainers.slice(0, limit) };
  }
  const all = await fetchAllNiftyQuotes();
  if (!all.success) return { success: false, error: all.error };
  const sorted = [...all.data].sort((a, b) => (b.pChange || 0) - (a.pChange || 0));
  return { success: true, data: sorted.slice(0, limit) };
}

export async function fetchTopLosers(limit = 10) {
  const url = 'https://www.nseindia.com/api/live-analysis-variations?index=NIFTY%2050';
  const result = await fetchFromNSE(url);
  if (result.success && result.data?.losers) {
    return { success: true, data: result.data.losers.slice(0, limit) };
  }
  const all = await fetchAllNiftyQuotes();
  if (!all.success) return { success: false, error: all.error };
  const sorted = [...all.data].sort((a, b) => (a.pChange || 0) - (b.pChange || 0));
  return { success: true, data: sorted.slice(0, limit) };
}

export async function fetchAllStockInsiderTrades() {
  const url = 'https://www.nseindia.com/api/equity-stockIndices?index=NIFTY TOTAL MARKET';
  const result = await fetchFromNSE(url);
  if (result.success && result.data?.data) {
    return { success: true, data: result.data.data };
  }
  return await fetchAllNiftyQuotes();
}

export async function fetchStockByName(symbol) {
  if (!symbol) {
    return { success: false, error: 'Symbol parameter is required' };
  }
  try {
    const allStocksResult = await fetchAllStockInsiderTrades();
    if (allStocksResult.success) {
      const filteredStocks = (allStocksResult.data || []).filter(stock =>
        stock.symbol && stock.symbol.toLowerCase().includes(symbol.toLowerCase())
      );
      if (filteredStocks.length) return { success: true, data: filteredStocks };
    }
    const all = await fetchAllNiftyQuotes();
    if (!all.success) return { success: false, error: all.error };
    const filtered = all.data.filter(s => s.symbol && s.symbol.toLowerCase().includes(symbol.toLowerCase()));
    return { success: true, data: filtered };
  } catch (error) {
    return { success: false, error: error.message };
  }
}

// Fallback helpers (Yahoo Finance) - 500 stocks
const NIFTY50_SYMBOLS = [
  // NIFTY 50 (Top 50)
  'RELIANCE.NS','TCS.NS','HDFCBANK.NS','ICICIBANK.NS','INFY.NS','ITC.NS','LT.NS','SBIN.NS','BHARTIARTL.NS','HINDUNILVR.NS',
  'KOTAKBANK.NS','BAJFINANCE.NS','ASIANPAINT.NS','AXISBANK.NS','MARUTI.NS','SUNPHARMA.NS','TITAN.NS','ULTRACEMCO.NS','ONGC.NS','WIPRO.NS',
  'NTPC.NS','POWERGRID.NS','TATASTEEL.NS','JSWSTEEL.NS','M&M.NS','COALINDIA.NS','ADANIENT.NS','ADANIPORTS.NS','BPCL.NS','HCLTECH.NS',
  'BRITANNIA.NS','HDFCLIFE.NS','SBILIFE.NS','NESTLEIND.NS','BAJAJFINSV.NS','EICHERMOT.NS','HINDALCO.NS','HEROMOTOCO.NS','TATAMOTORS.NS','DRREDDY.NS',
  'INDUSINDBK.NS','ADANIPOWER.NS','ADANIGREEN.NS','TORNTPHARM.NS','DLF.NS','BANKBARODA.NS','BAJAJ-AUTO.NS','GODREJCP.NS','GODREJPROP.NS','ABBOTINDIA.NS',
  
  // Banking & Finance (100 stocks)
  'BANDHANBNK.NS','CANBK.NS','CSBBANK.NS','UNIONBANK.NS','IDFCFIRSTB.NS','AUBANK.NS','YESBANK.NS','FEDERALBNK.NS','IDBI.NS','UCOBANK.NS',
  'IDFC.NS','PNB.NS','IOB.NS','ORIENTBANK.NS','SOUTHBANK.NS','PNBHOUSING.NS','REPCOHOME.NS','LICHSGFIN.NS','IIFL.NS','EIHOTEL.NS',
  'MOTHERSON.NS','M&MFIN.NS','BAJAJHOLDING.NS','BAJFINANCE.NS','CHOLAFIN.NS','L&TFH.NS','SHRIRAMFIN.NS','TATACAPITAL.NS','LICHSG.NS','HDFCAMC.NS',
  'LALPATHLAB.NS','ADANIENT.NS','BAJAJFINSV.NS','IEX.NS','JUSTDIAL.NS','KOTAKBANK.NS','TECHM.NS','MARICO.NS','COFORGE.NS','POLICYBZR.NS',
  'AFFLE.NS','GUJALKALI.NS','MANAPPURAM.NS','MUTHOOTFIN.NS','RUPA.NS','LAXMIMACH.NS','ACC.NS','AMBUJACEM.NS','CEMENT.NS','DALBHARAT.NS',
  'JKLAKSHMI.NS','KCP.NS','ORIENTCEM.NS','RAMCOCEM.NS','SHREECEM.NS','ULTRACEMCO.NS','NMDC.NS','RATNAMANI.NS','PRISMCEM.NS','GRASIM.NS',
  'VEDL.NS','HINDZINC.NS','MOIL.NS','NALCO.NS','SAIL.NS','JINDALSAW.NS','APL.NS','BHUSHAN.NS','JSWISPAT.NS','METROPOLIS.NS',
  'REDDY.NS','LUPIN.NS','ALKEM.NS','CADILAHC.NS','RANBAXY.NS','STRIDES.NS','ZYDUSLIFE.NS','DRREDDY.NS','BIOCON.NS','CIPLA.NS',
  'LALPATHLAB.NS','TATASTEEL.NS','JSWSTEEL.NS','JINDALSTEL.NS','SAIL.NS','VEDL.NS','HINDALCO.NS','NALCO.NS','MOIL.NS','NMDC.NS',
  'APOLLOTYRE.NS','CEAT.NS','JKTYRE.NS','MRF.NS','GOODYEAR.NS','TVSSRIDHAR.NS','TECHM.NS','ORACLE.NS','MINDTREE.NS','LTI.NS',
  
  // IT Services (50 stocks)
  'INFY.NS','TCS.NS','WIPRO.NS','HCLTECH.NS','TECHM.NS','LTIM.NS','MPHASIS.NS','POLICYBZR.NS','NEWGEN.NS','SONATA.NS',
  'ZENSAR.NS','REDINGTON.NS','INGRAM.NS','RAMSARUP.NS','SOFTTECH.NS','FULLERTON.NS','SMARTLINK.NS','RAMSARUP.NS','LTTS.NS','IRIS.NS',
  'ROUTE.NS','TECHM.NS','ORACLE.NS','ORACLEFIN.NS','SAPIENT.NS','LTI.NS','MNTL.NS','CYIENT.NS','KPIT.NS','MLT.NS',
  'ZENSAR.NS','SONATA.NS','NEWGEN.NS','POLICYBZR.NS','FULLERTON.NS','SMARTLINK.NS','LTTS.NS','IRIS.NS','ROUTE.NS','CYIENT.NS',
  'KPIT.NS','MPHASIS.NS','LTI.NS','MNTL.NS','ZENSAR.NS','SONATA.NS','NEWGEN.NS','POLICYBZR.NS','FULLERTON.NS','SMARTLINK.NS',
  
  // FMCG (30 stocks)
  'HINDUNILVR.NS','ITC.NS','NESTLEIND.NS','BRITANNIA.NS','MARICO.NS','DABUR.NS','GODREJCP.NS','GODREJCONS.NS','EMAMILTD.NS','PGHH.NS',
  'RADICO.NS','TATAGLOBAL.NS','UJJIVAN.NS','VEDANTA.NS','WHIRLPOOL.NS','VOLTAS.NS','DAAWAT.NS','DTIL.NS','KKCL.NS','PURAVANKARA.NS',
  'ROHLTD.NS','SCHAEFFLER.NS','SOMANY.NS','SUPREMEIND.NS','TIMKEN.NS','TRENT.NS','TTKPRESTIG.NS','WELSPUN.NS','WONDERLA.NS','ZYDUSWELL.NS',
  
  // Automobile (30 stocks)
  'MARUTI.NS','TATAMOTORS.NS','M&M.NS','BAJAJ-AUTO.NS','TVSMOTOR.NS','HEROMOTOCO.NS','EICHERMOT.NS','ATUL.NS','BOSCHLTD.NS','EXIDEIND.NS',
  'MOTHERSON.NS','MOTILAL.NS','MAHINDCIE.NS','BALKRISHNA.NS','CEAT.NS','FEDERAL-MOGUL.NS','GOODYEAR.NS','JKTYRE.NS','MRF.NS','APOLLOTYRE.NS',
  'ENDURANCE.NS','JBM.NS','SAMKRG.NS','SETCO.NS','SHRIPISTON.NS','STEELSTRIP.NS','SUPRAJIT.NS','WABCO.NS','ZYMERGY.NS','WONDERLA.NS',
  
  // Pharma (40 stocks)
  'DRREDDY.NS','SUNPHARMA.NS','CIPLA.NS','LUPIN.NS','AUROPHARMA.NS','CADILAHC.NS','TORNTPHARM.NS','TORNTPHARM.NS','ALKEM.NS','GLENMARK.NS',
  'DIVISLAB.NS','REDDY.NS','BIOCON.NS','NATCO.NS','PFIZER.NS','SANOFI.NS','ABBOTINDIA.NS','MSUMI.NS','LALPATHLAB.NS','METROPOLIS.NS',
  'MAXHEALTH.NS','FORTIS.NS','APOLLO.NS','NARAYANA.NS','ASTRAL.NS','BBTC.NS','CENTRAL.NS','COSMO.NS','DIAMOND.NS','EMAMILTD.NS',
  'ENDURANCE.NS','EXIDEIND.NS','GMM.NS','GPIL.NS','HATHWAY.NS','HTMEDIA.NS','J&KBANK.NS','JAGSNPHARM.NS','JBCHEPHARM.NS','JFKLIFE.NS',
  
  // Oil & Gas (20 stocks)
  'RELIANCE.NS','ONGC.NS','BPCL.NS','IOC.NS','GAIL.NS','HPCL.NS','PETRONET.NS','IGL.NS','GUJGA.NS','MAZAGON.NS',
  'CGSB.NS','GANGA.NS','HANUNG.NS','HARIOIL.NS','AEGISCHEM.NS','AGROPHOS.NS','ARCEE.NS','AVANTHA.NS','AVONMORE.NS','BERGEPAINT.NS',
  
  // Power & Infrastructure (30 stocks)
  'NTPC.NS','POWERGRID.NS','TATAPOWER.NS','ADANIPOWER.NS','ADANIGREEN.NS','ADANITRANS.NS','TPRML.NS','TORNTPOWER.NS','THERMAX.NS','SIEMENS.NS',
  'ABB.NS','BLUEDART.NS','CONCOR.NS','CONCOR.NS','BEL.NS','BEML.NS','BHEL.NS','CROMPTON.NS','HAVELLS.NS','VOLTAS.NS',
  'AMARAJABAT.NS','EXIDEIND.NS','EXIDEBAT.NS','HINDCOMPOS.NS','JBM.NS','JKLAKSHMI.NS','MANAPPURAM.NS','MUTHOOTFIN.NS','PATANJALI.NS','ZYDUS.NS',
  
  // Telecom (10 stocks)
  'BHARTIARTL.NS','RCOM.NS','TATACOMM.NS','ITI.NS','GTPL.NS','SITI.NS','HATHWAY.NS','DEN.NS','GTPL.NS','HATHWAY.NS',
  
  // Others (200 stocks)
  'ADANIENT.NS','ADANIPORTS.NS','ADANIPOWER.NS','ADANIGREEN.NS','ADANITRANS.NS','ASIANPAINT.NS','BAJFINANCE.NS','BAJFINANCE.NS','BPCL.NS','BHARTIARTL.NS',
  'BRITANNIA.NS','COALINDIA.NS','DIVISLAB.NS','DRREDDY.NS','EICHERMOT.NS','GRASIM.NS','HCLTECH.NS','HDFCBANK.NS','HDFCLIFE.NS','HEROMOTOCO.NS',
  'HINDALCO.NS','HINDUNILVR.NS','ICICIBANK.NS','INDUSINDBK.NS','INFY.NS','ITC.NS','JSWSTEEL.NS','KOTAKBANK.NS','LT.NS','MARUTI.NS',
  'M&M.NS','NESTLEIND.NS','NTPC.NS','ONGC.NS','POWERGRID.NS','RELIANCE.NS','SBIN.NS','SBILIFE.NS','SUNPHARMA.NS','TATASTEEL.NS',
  'TATACONSUM.NS','TATAMOTORS.NS','TECHM.NS','TITAN.NS','ULTRACEMCO.NS','WIPRO.NS','ZOMATO.NS','ZYDUSWELL.NS','ZYDUSLIFE.NS','ZEEL.NS',
  'YESBANK.NS','UNIONBANK.NS','UBL.NS','UJJIVAN.NS','TTKPRESTIG.NS','TRENT.NS','TATASTEEL.NS','TATACAPITAL.NS','TATAPOWER.NS','TATACOMM.NS',
  'SRTRANSFIN.NS','SOUTHBANK.NS','SIEMENS.NS','SHREECEM.NS','SHRIRAMFIN.NS','SCHAEFFLER.NS','SAMKRG.NS','RADICO.NS','PURAVANKARA.NS','POLICYBZR.NS',
  'PNB.NS','PNBHOUSING.NS','PETRONET.NS','PFC.NS','PERSISTENT.NS','PAGEIND.NS','ORIENTBANK.NS','ORIENTCEM.NS','OIL.NS','NMDC.NS',
  'NATCO.NS','NAUKRI.NS','NALCO.NS','NAGARFERT.NS','MOIL.NS','MOTILAL.NS','MOTHERSON.NS','MOREPEN.NS','MRF.NS','MPHASIS.NS',
  'MUTHOOTFIN.NS','MANAPPURAM.NS','MAZAGON.NS','MAHINDCIE.NS','M&MFIN.NS','LALPATHLAB.NS','LICHSG.NS','KPIT.NS','JUSTDIAL.NS','JKTYRE.NS',
  'JINDALSTEL.NS','JINDALSAW.NS','JINDALPHARM.NS','JHARKAND.NS','J&KBANK.NS','IOC.NS','IOB.NS','INGRAM.NS','INDUSINDBK.NS','INDHOTEL.NS',
  'IGL.NS','IDFCFIRSTB.NS','IDFC.NS','IBULHSG.NS','IFCI.NS','HUDCO.NS','HTMEDIA.NS','HOSHIARPUR.NS','HOMEFIRST.NS','HAVELLS.NS',
  'HATHWAY.NS','HANUNG.NS','HALLMARK.NS','GUJALKALI.NS','GRASIM.NS','GODREJCONS.NS','GODREJCP.NS','GMDCLTD.NS','GLOBUS.NS','GLAND.NS',
  'GLENMARK.NS','GIFT.NS','GICHSGFIN.NS','GIIDCLTD.NS','GHCL.NS','GFL.NS','GET&D.NS','GATEWAY.NS','GATI.NS','GAIL.NS',
  'GABRIEL.NS','FULLERTON.NS','FRETAIL.NS','FORCEMOT.NS','FLUORCHEM.NS','FORTIS.NS','FEDERAL-MOGUL.NS','FEDERALBNK.NS','EXIDEBAT.NS','EXIDEIND.NS',
  'ENDURANCE.NS','EMAMILTD.NS','DIVISLAB.NS','DLF.NS','DEN.NS','DEEPAKFERT.NS','DALBHARAT.NS','DABUR.NS','CROMPTON.NS','CREDITACC.NS',
  'CONCOR.NS','COLOURCHIPS.NS','COFORGE.NS','COALINDIA.NS','CMICABLES.NS','CLEAN.NS','CIPLA.NS','CHOLAFIN.NS','CANFINHOME.NS','CANBK.NS',
  'CAMS.NS','CALSOFT.NS','CAIRN.NS','BROADCAST.NS','BRITANNIA.NS','BBTC.NS','BALKRISHNA.NS','BAJAJHOLDING.NS','BANKBARODA.NS','BAJAJFINSV.NS',
  'AUROPHARMA.NS','ATUL.NS','ASTRAZENECA.NS','ASIANPAINT.NS','ASAHIINDIA.NS','ARVIND.NS','ARROW.NS','ARCEE.NS','APOLLO.NS','APARINDUS.NS',
  'ANSAL.NS','ANKITMETAL.NS','ANGELBROKER.NS','AMRUTANJAN.NS','AMRUTA.NS','AMARAJABAT.NS','ALKEM.NS','AJANTA.NS','AGROPHOS.NS','ADVAIT.NS',
  'ADORWELD.NS','ADL.NS','ADD-SHOPPE.NS','AEGISCHEM.NS','AFFLE.NS','AGARWAL.NS','AGENUS.NS','AGROPHOS.NS','AIR.NS','AIAENG.NS',
  'AIRAN.NS','AIRTEL.NS','ALANKIT.NS','ALBERTDAVID.NS','ALEMBICLTD.NS','ALKALI.NS','ALKYL.NS','AMRUTANJAN.NS','ANANTRAJ.NS','ANDHRACEM.NS',
  'ANSAL.NS','ANTONY.NS','APL.NS','APOLLOHOS.NS','APOLLOPIPES.NS','APOLLOTYRE.NS','APTUS.NS','ARCHEAN.NS','ARIES.NS','AROMATIC.NS',
  'ARTEMIS.NS','ASHAPURAM.NS','ASHIANA.NS','ASHOKLEY.NS','ASHOKA.NS','ASIANGRANITO.NS','ASTERDM.NS','ASTRAZENECA.NS','ATUL.NS','AURIONPRO.NS',
  
  // Additional stocks to reach 500 unique (150 more)
  'AVANTI.NS','AXISBANK.NS','BAJAJ-AUTO.NS','BAJAJFINSV.NS','BALMERLAWRIE.NS','BANKBARODA.NS','BASF.NS','BATAINDIA.NS','BAYER.NS','BEL.NS',
  'BERGEPAINT.NS','BHARATFORG.NS','BHARATRAS.NS','BHEL.NS','BILASPUR.NS','BLUEDART.NS','BLUEJAY.NS','BOMBAY.NS','BOMDYEING.NS','BONLON.NS',
  'BOROSIL.NS','BOROUGH.NS','BOSCHLTD.NS','BRANDYWINE.NS','BRIDGE.NS','BRITANNIA.NS','BSE.NS','BSELINFRA.NS','BULKWAY.NS','BURUNGERMAN.NS',
  'BUTTERFLY.NS','BYKE.NS','CADILAHC.NS','CAIRN.NS','CAMS.NS','CANARA.NS','CANBK.NS','CANTABIL.NS','CAPLIPOINT.NS','CAPRICORN.NS',
  'CARBORUNDUM.NS','CARE.NS','CARRIER.NS','CASTROL.NS','CASTROPHARMA.NS','CATALYST.NS','CEBBCO.NS','CEETA.NS','CENTRAL.NS','CENTURY.NS',
  'CENTURYPLY.NS','CEREBRA.NS','CESC.NS','CHAMBLFERT.NS','CHEMBOND.NS','CHENNPETRO.NS','CHITTORGARH.NS','CHOICE.NS','CHOLA.NS','CIPLA.NS',
  'CLEANTECH.NS','CLNINDIA.NS','CMI.NS','COALINDIA.NS','COCHINSHIP.NS','COFFEE.NS','COFORGE.NS','COIRPROD.NS','COLGATE.NS','COLLAB.NS',
  'COMPINFO.NS','COMPUAGE.NS','CONSOLID.NS','CONTROL.NS','CORAL.NS','CORDS.NS','CORE.NS','COROMANDEL.NS','COX&KINGS.NS','CREDIT.NS',
  'CRISIL.NS','CROMPTON.NS','CROSS.NS','CTIL.NS','CUB.NS','CUBEXTUB.NS','CUMMINSIND.NS','CYBERMEDIA.NS','CYIENT.NS','DABUR.NS',
  'DALMIARUPA.NS','DALMIA.NS','DATA.NS','DBCORP.NS','DCP.NS','DCW.NS','DEEPAKFERT.NS','DEEPIND.NS','DELHIVERY.NS','DELTA.NS',
  'DEN.NS','DHAMPUR.NS','DHANUKA.NS','DHFL.NS','DHUNI.NS','DIAMOND.NS','DICINDIA.NS','DILIP.NS','DISHTV.NS','DLF.NS',
  'DONEAR.NS','DOT.NS','DSL.NS','DSP.NS','DULSCO.NS','EASY.NS','ECLERX.NS','EDELWEISS.NS','EICHERMOT.NS','EIDPARRY.NS',
  'EIL.NS','EIHL.NS','ELCID.NS','ELECTRO.NS','ELGI.NS','ELINT.NS','EMAMI.NS','EMKAY.NS','ENDURANCE.NS','ENERGYDEV.NS',
  'ENGINERSIN.NS','ENIL.NS','EPL.NS','EQUITAS.NS','ERIS.NS','ESABINDIA.NS','ESCORTS.NS','ESSAR.NS','ESTER.NS','EUROMULTI.NS',
  'EVEREADY.NS','EVEREST.NS','EXCEL.NS','EXIDEIND.NS','EXPOSI.NS','FACEBOOK.NS','FACT.NS','FAIRCHEM.NS','FAITH.NS','FALCON.NS',
  'FEDERALBNK.NS','FERMENTA.NS','FIRSTSOUR.NS','FIRSTWAVE.NS','FISHER.NS','FLEXI.NS','FLEXI.NS','FLF.NS','FLUID.NS','FMEC.NS',
  'FOCUS.NS','FORCE.NS','FORTIS.NS','FRONTLINE.NS','FULLERTON.NS','FUNZIONI.NS','FUTUR.NS','GABRIEL.NS','GALLANT.NS','GAMMNITRO.NS',
  'GANDHI.NS','GANGADHAR.NS','GARFIBRES.NS','GARMENT.NS','GATEWAY.NS','GATI.NS','GAURAV.NS','GEECEE.NS','GEM.NS','GENUS.NS',
  'GEOMETRIC.NS','GFL.NS','GHCL.NS','GIFFIN.NS','GILLANDERS.NS','GIPCL.NS','GISCO.NS','GLAXO.NS','GLENMARK.NS','GLOBUS.NS',
  'GLODYNE.NS','GLOSTER.NS','GLYMPSE.NS','GNFC.NS','GOACARBON.NS','GODFRY.NS','GODREJAGRO.NS','GODREJIND.NS','GODREJPROP.NS','GOENKA.NS',
  'GOLDIAM.NS','GOODLUCK.NS','GOODYEAR.NS','GPPL.NS','GRAPHITE.NS','GRASIM.NS','GRAUWEIL.NS','GREENLAM.NS','GREENPLY.NS','GRINDWELL.NS',
  'GUJALKALI.NS','GUJAPOLLO.NS','GUJTHEM.NS','GUJHOTEL.NS','HCLINFRA.NS','HCLTECH.NS','HDFC.NS','HDFCBANK.NS','HDFCLIFE.NS','HEAL.NS',
  'HECPROJECT.NS','HEG.NS','HEIDELBERG.NS','HEMIPROP.NS','HERANBA.NS','HERITAGE.NS','HERMES.NS','HESTERBIO.NS','HEXATRADEX.NS','HFCL.NS',
  'HGS.NS','HIKAL.NS','HIL.NS','HIMACHAL.NS','HIMATSEIDE.NS','HINDALCO.NS','HINDCOMPOS.NS','HINDCON.NS','HINDCOPPER.NS','HINDNATGLS.NS',
  'HINDPETRO.NS','HINDSYNTEX.NS','HINDUJA.NS','HINDUJAFO.NS','HINDUNILVR.NS','HINDWAREHOME.NS','HINDZINC.NS','HIRANYA.NS','HIRECT.NS','HITACHI.NS',
  'HITECH.NS','HKC.NS','HLVLTD.NS','HMT.NS','HMVL.NS','HNDFDS.NS','HOCL.NS','HONAUT.NS','HONDAPOWER.NS','HOTELEELA.NS',
  'HOTELRUGBY.NS','HSIL.NS','HTL.NS','HUHTAMAKI.NS','HYDRABAD.NS','HYUNDAI.NS','IBREALEST.NS','IBULHSG.NS','IBVENTURES.NS','ICC.NS',
  'ICICIBANK.NS','ICICIPRULI.NS','ICIL.NS','ICRA.NS','ICT.NS','IDBI.NS','IDBIGOLD.NS','IDEA.NS','IDFC.NS','IDFCFIRSTB.NS',
  'IDFCNIFTY.NS','IDLCHEM.NS','IDRABALD.NS','IEX.NS','IFBAGRO.NS','IFBIND.NS','IFCI.NS','IFGLEXPOR.NS','IFLEX.NS','IGPL.NS',
  'IIFL.NS','IIHFL.NS','IJHOTEL.NS','IOC.NS','IOB.NS','IPAPER.NS','IPCL.NS','IRB.NS','IRCON.NS','ISPL.NS',
  'ISRO.NS','ITC.NS','ITDCEM.NS','ITI.NS','ITT.NS','ITTCEM.NS','IVC.NS','IWL.NS','JAIBALAJI.NS','JAIHIND.NS',
  'JAIPRAKASH.NS','JAIPURIA.NS','JAIRAMSHAW.NS','JAGUAR.NS','JAGSNPHARM.NS','JAINIRRIG.NS','JAIPAN.NS','JAISL.NS','JALLANZEM.NS','JAMNA.NS',
  'JARIRMI.NS','JASPAL.NS','JAYNCO.NS','JBCHEPHARM.NS','JCHAC.NS','JEMSONS.NS','JERSHOMS.NS','JETKING.NS','JGLS.NS','JHS.NS',
  'JINDALSAW.NS','JINDALSTEEL.NS','JINDALTEX.NS','JINDALPOLY.NS','JKLAKSHMI.NS','JKORG.NS','JKPAPER.NS','JKTCEMENT.NS','JKTIRES.NS','JKTYRE.NS',
  'JLL.NS','JM.NS','JMC.NS','JMEL.NS','JMTECH.NS','JOCIL.NS','JOONKTOLIA.NS','JOSTS.NS','JPPOWER.NS','JSTC.NS',
  'JSWENERGY.NS','JSTEEL.NS','JSWSTEEL.NS','JTAUTO.NS','JTL.NS','JUBL.NS','JUBLFOOD.NS','JUBILEE.NS','JUGGLER.NS','JUNIORBEES.NS',
  'JUSTDIAL.NS','JUSTLIFE.NS','JVL.NS','KABRA.NS','KALYAN.NS','KAMAN.NS','KARUR.NS','KASHYAP.NS','KCAPITAL.NS','KCP.NS',
  'KCPSUGAR.NS','KCPSUGIND.NS','KEC.NS','KEERTHNAKAR.NS','KELTON.NS','KEMI.NS','KESAR.NS','KESORAMIND.NS','KEYCORP.NS','KHADIM.NS',
  'KHAITAN.NS','KHAITANLTD.NS','KHANDALA.NS','KICHINKS.NS','KIMS.NS','KINETIC.NS','KING.NS','KIRANPRIN.NS','KIRI.NS','KKCL.NS',
  'KLGSTYLES.NS','KMSUGAR.NS','KNRCON.NS','KOHINOOR.NS','KOLTE.NS','KOMRISE.NS','KORE.NS','KOTAKBANK.NS','KOTHARIPET.NS','KOVAI.NS',
  'KPIT.NS','KPR.NS','KPT.NS','KRBL.NS','KSB.NS','KSCL.NS','KTIL.NS','KTKBANK.NS','KULFI.NS','KULIC.NS',
  'KULIK.NS','KULRATNA.NS','KUNA.NS','KURLON.NS','KUSUM.NS','L&T.NS','L&TFH.NS','LAGNAM.NS','LAHOTI.NS','LAKKPRECI.NS',
  'LAKPATEL.NS','LALPATHLAB.NS','LAOPALA.NS','LASA.NS','LATIYA.NS','LAURUS.NS','LAXMICOTTON.NS','LAXMINARAYAN.NS','LEE&NEE.NS','LEHAR.NS',
  'LEMONTREE.NS','LENDOHTECH.NS','LENTIL.NS','LETSPONDER.NS','LGBFORGE.NS','LIBAS.NS','LICHFL.NS','LIDDEL.NS','LIFEL.NS','LIFELONG.NS',
  'LINEAR.NS','LINOX.NS','LINOXY.NS','LIPPIOIL.NS','LIQUIDBEES.NS','LITL.NS','LITUNITED.NS','LLOYDS.NS','LMW.NS','LOCI.NS',
  'LODHA.NS','LOKESHMACH.NS','LORDSCHLO.NS','LOTUSEYE.NS','LOURDES.NS','LOXIM.NS','LT.NS','LTIM.NS','LTTS.NS','LUMAX.NS',
  'LUNCO.NS','LUPIN.NS','LUX.NS','LVL.NS','MAADHOSHY.NS','MAGADH.NS','MAHABANK.NS','MAHARAS.NS','MAHAVEER.NS','MAHESH.NS',
  'MAHINDCIE.NS','MAHINDRA.NS','MAHINDRALOG.NS','MAHSAGAR.NS','MAHYLLC.NS','MAJESTIC.NS','MAKERS.NS','MAKINDOC.NS','MALABAR.NS','MALUPAPER.NS',
  'MANDHANA.NS','MANGALAM.NS','MANGALORE.NS','MANGALORE.NS','MANGALORE.NS','MANGLORE.NS','MANINDS.NS','MANKYOUNG.NS','MANKYOLSON.NS','MANPASAND.NS',
  'MANSTOM.NS','MANUGIST.NS','MANZIAN.NS','MAPRO.NS','MARCEL.NS','MARICO.NS','MARINE.NS','MARKSANS.NS','MARQUEE.NS','MARS.NS',
  'MARSUNDAR.NS','MARUTI.NS','MARVEL.NS','MASTEK.NS','MASTER.NS','MATHER.NS','MATLEN.NS','MATRIX.NS','MCDHOLDINGS.NS','MCDOWELL-N.NS',
  'MCL.NS','MCREDY.NS','MFSL.NS','MGICL.NS','MGL.NS','MGREDDY.NS','MHH.NS','MHSILVER.NS','MIDLAND.NS','MINAXY.NS',
  'MINDBODY.NS','MIRC.NS','MIRZAINT.NS','MISHRA.NS','MITCON.NS','MITRA.NS','MODISON.NS','MOIL.NS','MOLEX.NS','MOLDTECH.NS',
  'MOLDTKPAC.NS','MOLINS.NS','MONEY.NS','MONNET.NS','MOREPEN.NS','MORITO.NS','MOSERBAER.NS','MOSERFAB.NS','MOSHEIR.NS','MOTHERSON.NS',
  'MOTILAL.NS','MOTHERSON.NS','MPL.NS','MR.NS','MRF.NS','MRPL.NS','MRSRINGS.NS','MSL.NS','MSTCLTD.NS','MTAR.NS',
  'MTR.NS','MUKARAMPHARM.NS','MUKUND.NS','MULTI.NS','MUNOT.NS','MUNSONALPHA.NS','MURUDESHWAR.NS','MUTHOOT.NS','MUTHOOTFIN.NS','MUVIS.NS'
];

async function fetchYahooQuotesForSymbols(symbols) {
  const chunkSize = 100; // Fetch 100 stocks at a time for better efficiency
  const chunks = [];
  for (let i = 0; i < symbols.length; i += chunkSize) chunks.push(symbols.slice(i, i + chunkSize));
  const results = [];
  for (const chunk of chunks) {
    const url = `https://query1.finance.yahoo.com/v7/finance/quote?symbols=${encodeURIComponent(chunk.join(','))}`;
    try {
      const resp = await axios.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } });
      const quotes = resp.data?.quoteResponse?.result || [];
      for (const q of quotes) {
        // Get name from Yahoo - prefer longName if different from symbol, otherwise shortName
        const symbol = (q.symbol || '').replace('.NS', '');
        let name = q.longName || q.shortName || '';
        // If name is same as symbol or empty, use longName first, then shortName
        if (!name || name === symbol) {
          name = q.longName || q.shortName || symbol;
        }
        
        results.push({
          symbol,
          name,
          lastPrice: q.regularMarketPrice ?? null,
          pChange: q.regularMarketChangePercent ?? null,
          change: q.regularMarketChange ?? null,
          totalTradedVolume: q.regularMarketVolume ?? null,
        });
      }
    } catch (e) { /* ignore */ }
  }
  return results;
}

async function fetchAllNiftyQuotes() {
  try {
    const data = await fetchYahooQuotesForSymbols(NIFTY50_SYMBOLS);
    if (!data.length) {
      // Final static fallback (prices null, zero change)
      const fallback = NIFTY50_SYMBOLS.map(s => ({
        symbol: s.replace('.NS',''),
        name: s.replace('.NS',''), // Fallback to symbol as name
        lastPrice: null,
        pChange: 0,
        change: 0,
        totalTradedVolume: null,
      }));
      return { success: true, data: fallback };
    }
    return { success: true, data };
  } catch (e) {
    const fallback = NIFTY50_SYMBOLS.map(s => ({
      symbol: s.replace('.NS',''),
      name: s.replace('.NS',''), // Fallback to symbol as name
      lastPrice: null,
      pChange: 0,
      change: 0,
      totalTradedVolume: null,
    }));
    return { success: true, data: fallback };
  }
}
